stages:
  - mirror

mirror_to_github:
  stage: mirror
  image: alpine:latest
  script:
    - git remote add github "https://${GITHUB_TOKEN}@github.com/cevochka-js/cevochka-js.github.io.git"
    - git push github master:main --force
  only:
    - master
